const PADDING = 8;
const MARGIN = 16;

const FULL_SCREEN_HEIGHT_TABLE_CONTAINER = `calc(100dvh - ${MARGIN * 2}px)`;
const FULL_SCREEN_HEIGHT_TABLE = `calc(100dvh - ${MARGIN * 2 + PADDING * 2}px)`;

export const FULL_SCREEN = {
  TOP: `${MARGIN}px`,
  LEFT: `${MARGIN}px`,
  MARGIN: `${MARGIN}px`,
  BOX_SHADOW: `${MARGIN * 4}px`,
  PADDING,
  HEIGHT_TABLE_CONTAINER: FULL_SCREEN_HEIGHT_TABLE_CONTAINER,
  HEIGHT_TABLE: FULL_SCREEN_HEIGHT_TABLE,
  WIDTH_TABLE_CONTAINER: `calc(100vw - ${MARGIN * 2}px)`,
} as const;
