export const DETAIL_KEYS = {
  IS_HAVE: 'SERVICE_IS_HAVE_DETAIL',
  IS_HAVE_EXPANDED: 'SERVICE_IS_HAVE_EXPANDED',
  //
  IS_DETAIL_PANEL_ROW: 'SERVICE_IS_DETAIL_PANEL_ROW',
  ROW_DATA: 'SERVICE_ROW_DATA',
  ROW_DETAIL_RENDER: 'SERVICE_ROW_DETAIL_RENDER',
  //
  ROW_DETAIL_RENDER_EDITING: 'SERVICE_ROW_DETAIL_RENDER_EDITING',
  EXPAND_ICON_BUTTON_PROPS: 'SERVICE_EXPAND_ICON_BUTTON_PROPS',
  EXPAND_ICON_CLOSED: 'SERVICE_EXPAND_ICON_CLOSED',
  EXPAND_ICON_OPENED: 'SERVICE_EXPAND_ICON_OPENED',
  ROW_DETAIL_IS_EDITABLE: 'SERVICE_ROW_DETAIL_IS_EDITABLE',
} as const;

const { IS_DETAIL_PANEL_ROW, ROW_DATA, ROW_DETAIL_RENDER } = DETAIL_KEYS;

export const DETAIL_PANEL_KEYS = {
  IS_DETAIL_PANEL_ROW,
  ROW_DATA,
  ROW_DETAIL_RENDER,
} as const;

const {
  EXPAND_ICON_BUTTON_PROPS,
  EXPAND_ICON_CLOSED,
  EXPAND_ICON_OPENED,
  IS_HAVE,
  IS_HAVE_EXPANDED,
} = DETAIL_KEYS;

export const ROW_WITH_DETAIL_DETAIL_KEYS = {
  EXPAND_ICON_BUTTON_PROPS,
  EXPAND_ICON_CLOSED,
  EXPAND_ICON_OPENED,
  IS_HAVE,
  IS_HAVE_EXPANDED,
} as const;
